config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'flats#index'

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for [ flat ] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "#{update ? 'Update' : 'Add'} flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/index.html.erb
<main class="py-5 px-4">
  <div class="container w-80">
    <h2 class="fw-bold">Find the perfect flat for you!</h2>

      <section class="flats">
        <% @flats.each do |flat| %>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <p class="card-title fs-4"><%= flat.name %></p>
              <p class="card-text"><%= flat.description %></p>
              <p class="card-text">
                <span><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %></span>
                <span><i class="fas fa-dollar-sign"></i> <%= flat.price_per_night %></span>
              </p>
              <%= link_to 'More info', flat_path(flat), class: 'btn btn-outline-primary' %>
            </div>
          </div>
        <% end %>
      </section>

  </div>
</main>

app/views/flats/new.html.erb
<main class="py-5 px-4">
  <div class="container w-80">
    <h2 class="fw-bold">New flat</h2>
    <%= render 'form', flat: @flat, update: false %>
    <%= link_to 'Cancel', root_path, class: 'btn btn-light' %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "partials/header" %>
    <%= yield %>
    <%= render partial: "partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="bg-primary text-white p-5 text-center">
  <div class="container w-80">
    <small>coded in a hurry</small>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="py-5 px-4 bg-light">
  <div class="container w-80">
    <div class="row">
      <div class="col-6 text-start fs-4 text">
        <%= link_to 'Simple Airbnb', root_path, class: 'text-reset text-decoration-none' %>
      </div>

      <div class="col-6 text-end">
        <%= link_to 'Add flat', new_flat_path, class: 'btn btn-outline-primary' %>
      </div>
    </div>
  </div>
</header>